start-at-login = true

# using homebrew to bootstrap borders
# after-startup-command = [
#   'exec-and-forget borders',
# ]

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = true

[gaps]
inner.horizontal = 2
inner.vertical = 2
outer.left = 2
outer.bottom = 2
outer.top = 2
outer.right = 2

[workspace-to-monitor-force-assignment]
A = 'secondary'
S = 'secondary'
D = 'secondary'
F = 'secondary'

[mode.main.binding]

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
# bad interaction with CSA keyboard
# TODO: find another keybinding
alt-shift-ctrl-t = 'layout tiles horizontal vertical'
# alt-comma = 'layout accordion horizontal vertical'

# focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# resize
alt-shift-ctrl-minus = 'resize smart -50'
alt-shift-ctrl-equal = 'resize smart +50'
alt-shift-cmd-ctrl-minus = 'resize smart -200'
alt-shift-cmd-ctrl-equal = 'resize smart +200'

# workspace management
alt-shift-cmd-ctrl-1 = 'workspace 1'
alt-shift-cmd-ctrl-2 = 'workspace 2'
alt-shift-cmd-ctrl-3 = 'workspace 3'
alt-shift-cmd-ctrl-4 = 'workspace 4'
alt-shift-cmd-ctrl-5 = 'workspace 5'
alt-shift-cmd-ctrl-6 = 'workspace 6'
alt-shift-cmd-ctrl-7 = 'workspace 7'
alt-shift-cmd-ctrl-8 = 'workspace 8'
alt-shift-cmd-ctrl-9 = 'workspace 9'
alt-shift-cmd-ctrl-0 = 'workspace 0'
alt-shift-cmd-ctrl-a = 'workspace A'
alt-shift-cmd-ctrl-s = 'workspace S'
alt-shift-cmd-ctrl-d = 'workspace D'
alt-shift-cmd-ctrl-f = 'workspace F'

alt-shift-ctrl-1 = 'move-node-to-workspace 1'
alt-shift-ctrl-2 = 'move-node-to-workspace 2'
alt-shift-ctrl-3 = 'move-node-to-workspace 3'
alt-shift-ctrl-4 = 'move-node-to-workspace 4'
alt-shift-ctrl-5 = 'move-node-to-workspace 5'
alt-shift-ctrl-6 = 'move-node-to-workspace 6'
alt-shift-ctrl-7 = 'move-node-to-workspace 7'
alt-shift-ctrl-8 = 'move-node-to-workspace 8'
alt-shift-ctrl-9 = 'move-node-to-workspace 9'
alt-shift-ctrl-0 = 'move-node-to-workspace 0'
alt-shift-ctrl-a = 'move-node-to-workspace A'
alt-shift-ctrl-s = 'move-node-to-workspace S'
alt-shift-ctrl-d = 'move-node-to-workspace D'
alt-shift-ctrl-f = 'move-node-to-workspace F'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-semicolon = 'mode service'

alt-ctrl-shift-h = ['join-with left', 'mode main']
alt-ctrl-shift-j = ['join-with down', 'mode main']
alt-ctrl-shift-k = ['join-with up', 'mode main']
alt-ctrl-shift-l = ['join-with right', 'mode main']

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = [
  'layout floating tiling',
  'mode main',
] 

[[on-window-detected]]
if.window-title-regex-substring = "Karabiner"
run = ["layout floating"]
