background = 0xFF1D202B
base = 0xFF202A3A
text = 0xFFC8D3F5
alternate_base = 0xFF404552
bright_text = 0xFFFFDEDE
accent = 0xFF0070FF
accent_secondary = 0xFF00A0FF
font_family = Monaspace Neon
font_family_monospace = Monaspace Neon
