
# rofi drun
windowrule = float true, match:title rofi
windowrule = center true, match:title rofi
#Apple Music
#windowrule = float true, match:title Apple Music
#windowrule = center, match:title Apple Music
#windowrule = size 1920 1080, match:title Apple Music
windowrule = float true, match:title ^(pavucontrol)$
windowrule = float true, match:title ^(btop)$

windowrule = float true, match:title ^(update-sys)$
windowrule = match:title ^(.*(Disney+|YouTube).*)$, opaque true
