[Service]
ExecStart=
ExecStart=-/usr/bin/agetty -o '-p -- steve' --noclear --skip-login --issue-file=/etc/issue:/etc/issue.d:/run/issue.d:/usr/lib/issue.d - ${TERM}

; Environment=XDG_SESSION_TYPE=wayland
