return {
    "williamboman/mason.nvim",
    opts_extend = { "ensure_installed" },
    opts = {
        ensure_installed = {
            "css-lsp",
            "docker-compose-language-service",
            "dockerfile-language-server",
            "emmet-ls",
            "eslint-lsp",
            "hadolint",
            "html-lsp",
            "htmx-lsp",
            "jinja-lsp",
            "js-debug-adapter",
            "json-lsp",
            "lua-language-server",
            "markdown-toc",
            "markdownlint-cli2",
            "marksman",
            "prettier",
            "pyright",
            "ruff",
            "shfmt",
            "stylua",
            "tailwindcss-language-server",
            "taplo",
            "vtsls",
            "vue-language-server",
            "yaml-language-server",
        },
    },
}
