local servers = {
	"css-lsp",
	"docker-compose-language-service",
	"dockerfile-language-server",
	-- "emmet-ls",
	"eslint-lsp",
	"flake8",
	"html-lsp",
	"htmx-lsp",
	"jinja-lsp",
	"json-lsp",
	"lua-language-server",
	"markdown-toc",
	"markdownlint-cli2",
	"marksman",
	"prettier",
	"pyright",
	-- "basedpyright",
	"ruff",
	-- "rust-analyzer",
	"shfmt",
	"stylua",
	"tailwindcss-language-server",
	"taplo",
	"vtsls",
	"vue-language-server",
	"yaml-language-server",
}

return { }
